---
name: 'Build docker images'
on:
  push:
    branches: ['main']
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-and-push.yml'
  schedule:
    - cron: '0 1 1 * *'

jobs:
  docker:
    name: 'Build and push'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - tag: 'latest'
          - tag: '10.1.0'
          - tag: '10.0.1'
          - tag: '9.7.0'

    steps:
      - name: 'Checkout the codebase'
        uses: 'actions/checkout@v4'

      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@v3'

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Login to DockerHub'
        uses: 'docker/login-action@v3'
        with:
          username: 'antmelekhin'
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 'Build and push ${{ matrix.tag }}'
        uses: 'docker/build-push-action@v6'
        with:
          context: .
          file: 'Dockerfile'
          build-args: ANSIBLE_VERSION=${{ matrix.tag }}
          platforms: 'linux/amd64'
          push: true
          tags: 'antmelekhin/docker-ansible:${{ matrix.tag }}'
